apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - externalsecret.yaml
  - externalsecret-oidc.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - deployment-oauth2-proxy.yaml
  - service-oauth2-proxy.yaml
  - httproute.yaml
